// File generated by FlutterFire CLI.                      // Arquivo gerado automaticamente pelo FlutterFire CLI
// ignore_for_file: type=lint                             // Ignora avisos de lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions; // Importa FirebaseOptions para configurar Firebase
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;   // Importa constantes para identificar plataforma atual

class DefaultFirebaseOptions {                            // Classe que contém opções de configuração do Firebase
  static FirebaseOptions get currentPlatform {            // Retorna configuração correta conforme plataforma
    if (kIsWeb) {
      return web;                                         // Se for Web → usa configuração web
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;                                   // Se for Android → usa configuração android
      case TargetPlatform.iOS:
        return ios;                                       // Se for iOS → usa configuração ios
      case TargetPlatform.macOS:
        throw UnsupportedError(                           // macOS não configurado
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(                           // Windows não configurado
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(                           // Linux não configurado
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(                           // Qualquer outra plataforma não suportada
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(     // Configuração para Web
    apiKey: 'AIzaSyD8FANvbLPOekFILrEXLg0dvlmua8ur_vw',    // Chave de API
    appId: '1:21931884224:web:007c46959a9910825c7725',    // ID do app
    messagingSenderId: '21931884224',                     // ID para mensagens (FCM)
    projectId: 'lojafatec',                               // ID do projeto Firebase
    authDomain: 'lojafatec.firebaseapp.com',              // Domínio de autenticação
    storageBucket: 'lojafatec.firebasestorage.app',       // Bucket de armazenamento
    measurementId: 'G-030C5T7GEG',                        // ID de medição (Analytics)
  );

  static const FirebaseOptions android = FirebaseOptions( // Configuração para Android
    apiKey: 'AIzaSyBMZNN2ydLpSvGlNlQ3f_DrqshUlUM504U',
    appId: '1:21931884224:android:ddee0572c73bdd215c7725',
    messagingSenderId: '21931884224',
    projectId: 'lojafatec',
    storageBucket: 'lojafatec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(     // Configuração para iOS
    apiKey: 'AIzaSyCGuv80_UaEifSrszrPDt6CbdgySi2vPfY',
    appId: '1:21931884224:ios:3d7a250704cd8d935c7725',
    messagingSenderId: '21931884224',
    projectId: 'lojafatec',
    storageBucket: 'lojafatec.firebasestorage.app',
    iosBundleId: 'com.example.lojaP2',                   // Bundle ID do app iOS
  );
}
